from enum import Enum

class ForecastCurrent(Enum):
    CATEGORY = 'current'
    TEMPERATURE_2M = 'temperature_2m'
    RELATIVE_HUMIDITY_2M = 'relative_humidity_2m'
    APPARENT_TEMPERATURE = 'apparent_temperature'
    IS_DAY = 'is_day'
    PRECIPITATION = 'precipitation'
    RAIN = 'rain'
    SHOWERS = 'showers'
    SNOWFALL = 'snowfall'
    WEATHER_CODE = 'weather_code'
    CLOUD_COVER = 'cloud_cover'
    PRESSURE_MSL = 'pressure_msl'
    SURFACE_PRESSURE = 'surface_pressure'
    WIND_SPEED_10M = 'wind_speed_10m'
    WIND_DIRECTION_10M = 'wind_direction_10m'
    WIND_GUSTS_10M = 'wind_gusts_10m'

class ForecastMinutely15(Enum):
    CATEGORY = 'minutely_15'
    TEMPERATURE_2M='temperature_2m'
    RELATIVE_HUMIDITY_2M='relative_humidity_2m'
    DEW_POINT_2M='dew_point_2m'
    APPARENT_TEMPERATURE='apparent_temperature'
    PRECIPITATION='precipitation'
    RAIN='rain'
    SNOWFALL='snowfall'
    SNOWFALL_HEIGHT='snowfall_height'
    FREEZING_LEVEL_HEIGHT='freezing_level_height'
    SUNSHINE_DURATION='sunshine_duration'
    WEATHER_CODE='weather_code'
    WIND_SPEED_10M='wind_speed_10m'
    WIND_SPEED_80M='wind_speed_80m'
    WIND_DIRECTION_10M='wind_direction_10m'
    WIND_DIRECTION_80M='wind_direction_80m'
    WIND_GUSTS_10M='wind_gusts_10m'
    VISIBILITY='visibility'
    CAPE='cape'
    LIGHTNING_POTENTIAL='lightning_potential'
    IS_DAY='is_day'
    SHORTWAVE_RADIATION='shortwave_radiation'
    DIRECT_RADIATION='direct_radiation'
    DIFFUSE_RADIATION='diffuse_radiation'
    DIRECT_NORMAL_IRRADIANCE='direct_normal_irradiance'
    GLOBAL_TILTED_IRRADIANCE='global_tilted_irradiance'
    TERRESTRIAL_RADIATION='terrestrial_radiation'
    SHORTWAVE_RADIATION_INSTANT='shortwave_radiation_instant'
    DIRECT_RADIATION_INSTANT='direct_radiation_instant'
    DIFFUSE_RADIATION_INSTANT='diffuse_radiation_instant'
    DIRECT_NORMAL_IRRADIANCE_INSTANT='direct_normal_irradiance_instant'
    GLOBAL_TILTED_IRRADIANCE_INSTANT='global_tilted_irradiance_instant'
    TERRESTRIAL_RADIATION_INSTANT='terrestrial_radiation_instant'    

class ForecastHourly(Enum):
    CATEGORY = 'hourly'
    TEMPERATURE_2M='temperature_2m'
    RELATIVE_HUMIDITY_2M='relative_humidity_2m'
    DEW_POINT_2M='dew_point_2m'
    APPARENT_TEMPERATURE='apparent_temperature'
    PRECIPITATION_PROBABILITY='precipitation_probability'
    PRECIPITATION='precipitation'
    RAIN='rain'
    SHOWERS='showers'
    SNOWFALL='snowfall'
    SNOW_DEPTH='snow_depth'
    WEATHER_CODE='weather_code'
    PRESSURE_MSL='pressure_msl'
    SURFACE_PRESSURE='surface_pressure'
    CLOUD_COVER='cloud_cover'
    CLOUD_COVER_LOW='cloud_cover_low'
    CLOUD_COVER_MID='cloud_cover_mid'
    CLOUD_COVER_HIGH='cloud_cover_high'
    VISIBILITY='visibility'
    EVAPOTRANSPIRATION='evapotranspiration'
    ET0_FAO_EVAPOTRANSPIRATION='et0_fao_evapotranspiration'
    VAPOUR_PRESSURE_DEFICIT='vapour_pressure_deficit'
    WIND_SPEED_10M='wind_speed_10m'
    WIND_SPEED_80M='wind_speed_80m'
    WIND_SPEED_120M='wind_speed_120m'
    WIND_SPEED_180M='wind_speed_180m'
    WIND_DIRECTION_10M='wind_direction_10m'
    WIND_DIRECTION_80M='wind_direction_80m'
    WIND_DIRECTION_120M='wind_direction_120m'
    WIND_DIRECTION_180M='wind_direction_180m'
    WIND_GUSTS_10M='wind_gusts_10m'
    TEMPERATURE_80M='temperature_80m'
    TEMPERATURE_120M='temperature_120m'
    TEMPERATURE_180M='temperature_180m'
    SOIL_TEMPERATURE_0CM='soil_temperature_0cm'
    SOIL_TEMPERATURE_6CM='soil_temperature_6cm'
    SOIL_TEMPERATURE_18CM='soil_temperature_18cm'
    SOIL_TEMPERATURE_54CM='soil_temperature_54cm'
    SOIL_MOISTURE_0_TO_1CM='soil_moisture_0_to_1cm'
    SOIL_MOISTURE_1_TO_3CM='soil_moisture_1_to_3cm'
    SOIL_MOISTURE_3_TO_9CM='soil_moisture_3_to_9cm'
    SOIL_MOISTURE_9_TO_27CM='soil_moisture_9_to_27cm'
    SOIL_MOISTURE_27_TO_81CM='soil_moisture_27_to_81cm'
    UV_INDEX='uv_index'
    UV_INDEX_CLEAR_SKY='uv_index_clear_sky'
    IS_DAY='is_day'
    SUNSHINE_DURATION='sunshine_duration'
    WET_BULB_TEMPERATURE_2M='wet_bulb_temperature_2m'
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR='total_column_integrated_water_vapour'
    CAPE='cape'
    LIFTED_INDEX='lifted_index'
    CONVECTIVE_INHIBITION='convective_inhibition'
    FREEZING_LEVEL_HEIGHT='freezing_level_height'
    BOUNDARY_LAYER_HEIGHT='boundary_layer_height'    
    
class ForecastDaily(Enum):
    CATEGORY = 'daily'
    WEATHER_CODE='weather_code'
    TEMPERATURE_2M_MAX='temperature_2m_max'
    TEMPERATURE_2M_MIN='temperature_2m_min'
    APPARENT_TEMPERATURE_MAX='apparent_temperature_max'
    APPARENT_TEMPERATURE_MIN='apparent_temperature_min'
    SUNRISE='sunrise'
    SUNSET='sunset'
    DAYLIGHT_DURATION='daylight_duration'
    SUNSHINE_DURATION='sunshine_duration'
    UV_INDEX_MAX='uv_index_max'
    UV_INDEX_CLEAR_SKY_MAX='uv_index_clear_sky_max'
    PRECIPITATION_SUM='precipitation_sum'
    RAIN_SUM='rain_sum'
    SHOWERS_SUM='showers_sum'
    SNOWFALL_SUM='snowfall_sum'
    PRECIPITATION_HOURS='precipitation_hours'
    PRECIPITATION_PROBABILITY_MAX='precipitation_probability_max'
    WIND_SPEED_10M_MAX='wind_speed_10m_max'
    WIND_GUSTS_10M_MAX='wind_gusts_10m_max'
    WIND_DIRECTION_10M_DOMINANT='wind_direction_10m_dominant'
    SHORTWAVE_RADIATION_SUM='shortwave_radiation_sum'
    ET0_FAO_EVAPOTRANSPIRATION='et0_fao_evapotranspiration'

class HistoricalHourly(Enum):
    TEMPERATURE_2M='temperature_2m'
    RELATIVE_HUMIDITY_2M='relative_humidity_2m'
    DEW_POINT_2M='dew_point_2m'
    APPARENT_TEMPERATURE='apparent_temperature'
    PRECIPITATION='precipitation'
    RAIN='rain'
    SNOWFALL='snowfall'
    SNOW_DEPTH='snow_depth'
    WEATHER_CODE='weather_code'
    PRESSURE_MSL='pressure_msl'
    SURFACE_PRESSURE='surface_pressure'
    CLOUD_COVER='cloud_cover'
    CLOUD_COVER_LOW='cloud_cover_low'
    CLOUD_COVER_MID='cloud_cover_mid'
    CLOUD_COVER_HIGH='cloud_cover_high'
    ET0_FAO_EVAPOTRANSPIRATION='et0_fao_evapotranspiration'
    VAPOUR_PRESSURE_DEFICIT='vapour_pressure_deficit'
    WIND_SPEED_10M='wind_speed_10m'
    WIND_SPEED_100M='wind_speed_100m'
    WIND_DIRECTION_10M='wind_direction_10m'
    WIND_DIRECTION_100M='wind_direction_100m'
    WIND_GUSTS_10M='wind_gusts_10m'
    SOIL_TEMPERATURE_0_TO_7CM='soil_temperature_0_to_7cm'
    SOIL_TEMPERATURE_7_TO_28CM='soil_temperature_7_to_28cm'
    SOIL_TEMPERATURE_28_TO_100CM='soil_temperature_28_to_100cm'
    SOIL_TEMPERATURE_100_TO_255CM='soil_temperature_100_to_255cm'
    SOIL_MOISTURE_0_TO_7CM='soil_moisture_0_to_7cm'
    SOIL_MOISTURE_7_TO_28CM='soil_moisture_7_to_28cm'
    SOIL_MOISTURE_28_TO_100CM='soil_moisture_28_to_100cm'
    SOIL_MOISTURE_100_TO_255CM='soil_moisture_100_to_255cm'
    BOUNDARY_LAYER_HEIGHT='boundary_layer_height'
    WET_BULB_TEMPERATURE_2M='wet_bulb_temperature_2m'
    TOTAL_COLUMN_INTEGRATED_WATER_VAPOUR='total_column_integrated_water_vapour'
    IS_DAY='is_day'
    SUNSHINE_DURATION='sunshine_duration'
    ALBEDO='albedo'
    SNOW_DEPTH_WATER_EQUIVALENT='snow_depth_water_equivalent'

class HistoricalDaily(Enum):
    WEATHER_CODE='weather_code'
    TEMPERATURE_2M_MAX='temperature_2m_max'
    TEMPERATURE_2M_MIN='temperature_2m_min'
    TEMPERATURE_2M_MEAN='temperature_2m_mean'
    APPARENT_TEMPERATURE_MAX='apparent_temperature_max'
    APPARENT_TEMPERATURE_MIN='apparent_temperature_min'
    APPARENT_TEMPERATURE_MEAN='apparent_temperature_mean'
    SUNRISE='sunrise'
    SUNSET='sunset'
    DAYLIGHT_DURATION='daylight_duration'
    SUNSHINE_DURATION='sunshine_duration'
    PRECIPITATION_SUM='precipitation_sum'
    RAIN_SUM='rain_sum'
    SNOWFALL_SUM='snowfall_sum'
    PRECIPITATION_HOURS='precipitation_hours'
    WIND_SPEED_10M_MAX='wind_speed_10m_max'
    WIND_GUSTS_10M_MAX='wind_gusts_10m_max'
    WIND_DIRECTION_10M_DOMINANT='wind_direction_10m_dominant'
    SHORTWAVE_RADIATION_SUM='shortwave_radiation_sum'
    ET0_FAO_EVAPOTRANSPIRATION='et0_fao_evapotranspiration'

__all__ = [
    'ForecastCurrent',
    'ForecastMinutely15',
    'ForecastHourly',
    'ForecastDaily',
    'HistoricalHourly',
    'HistoricalDaily'
]